### ISSUE TITLE
syncing to a directory unexpectedly clears the directory

### ISSUE THREAD

**Issue by mbaumgart** [NickRimmer/insomnia-plugin-free-sync#24]
## Description of the issue
Because the sync directory is the default option, I selected a directory on my system to sync to, expecting Free Sync to just drop the generated files to sync into there, just like you specify home directories in other tools. Unfortunately for me I selected my projects directory for this.
After hitting "Save workspace" I found that my whole projects directory was deleted and overwritten with Free Sync files.

## Expected Result
I would have expected for Free Sync to not erase the directory contents and instead just create the self-managed files or directories there.

**Comment by NickRimmer** [comment]
Good point 👍 we can save resource folders in meta file, and clean them only

**Comment by kolbeypruitt** [comment]
This tool wiped every directory that I have an insomnia file in.. DO NOT RECOMMEND use until this is resolved.

**Comment by kolbeypruitt** [comment]
In fact it cleared data from all over my macbook's drive. I am going to have to restore it because apps are not functioning properly after seemingly random files were destroyed.

**Comment by NickRimmer** [comment]
I will find a time to fix it as fast as possible 😨

**Comment by NickRimmer** [comment]
As I understood, it will store everything in a subfolder which will not make the user safe from putting other files that will be removed on synchronization. So generally it will force a user to use a specific folder for insomnia settings instead of some project folder.

I see a couple of possible issues with it
- it will not entirely prevent removing of user's files not related to Insomnia
- when a user configures the folder for synchronization for the first time, it will confuse that need to select not "insomnia" folder, but a parent.

I will try to play a bit with logic, to find some solution in a middle and let you back soon (=

**Comment by NickRimmer** [comment]
Hey! Just a heads-up that I'm closing old tickets and archiving this repo. I've started working on my own client, where I'll be applying all the ideas I wanted to bring here 😊

It's called [RestApia](https://www.restapia.app/). Feel free to check it out!
